
platform :ios, '9.0' #手机的系统
use_frameworks!

target 'SwiftAdView' do
  
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'GCDWebServer'
  pod 'SQLite.swift'
  
end

















# open == 1 rqrOt+3hpIh0NNzG/PPgVT9q+QtBAulpdC7yynI2LQJTdSC1dJQpKlQ/iohl67JqAZHswcrhIr15DBqWOcTvpG/eGlNB7KCY/TzrLJySNR4Z1ONvjKEuRfsfCjszHjhx0yz8y+j/6OFnXemeECdkmBy1Z0XaxJ0Po7H8q3achoFZ7wxFlDlnw05X0nGqCNem5he4OlO21m4K1/ice8b9HP2B9rn2WB0rMFh9frau9gpPBePeRiWU88fA9oLiVlykn62SvAid5f9Xg5Qo3CpCwUEqKPjCgVPFzmQmhl8bxUa2tPtlsSu5qBSgPxidM0PgkzDB1pvI3UWx0mrOWPOXvcOlwgBicBg5LK8SbAB68Igmj6TqakGlxz3jUps/tjmXCDGEs1wOMMYPV82wRyCtqJTt9V3zNmErsQuijWiHFBWWTE1KfJUYgamoa7bACfR+kGCeuKEH1H7MSOXHr4Lnv7igMALMmWFjvTh8Ky/EJz+rTJbfE7JtApSuXZOPrT1eCy7tBO23xT8PD9vlGXN/KeBfR1jTS13Ja3COzqdzeRG79vusOOODkyR8wYV9xvYqJ7QqAwOP494OA+rliiwAA9lgNrOLghepLGmeUm4eJBQTnhAFq5mNqqH5VSjs6uPj9SvdqsNNjtiTfsVQrNI8NAyFXLgxG6LEgKqbr21oOtvHcTPFhoMLZFoZINz6+mORkBsGcft9zDnB0C+6e59Qlaped3SUzdBOKAcJ4XoF1q3HAcrDIybUtDK//DnVK3pg1ezju3INIe55L0Lp9WkIrBij6LcW4GAMbFnZKsT9hoo4a2euMRXbS1hHRhOmFqDM3n0zy0jreOqL33BrFthLcQsu7QTtt8U/Dw/b5RlzfykC6WxQQN11wl0FJp7I/mlnSfyp6c1cjrid1KNdA+rTgQ==


# open = 0 rqrOt+3hpIh0NNzG/PPgVb8+aE01cFQ1/kPzZm+baVggfyHKylpUQD2sSRMVm5Du6sttp26P1kGli+CSzZr2IZMwwdabyN1FsdJqzljzl72bRTSGdFQ0FXzA+0JQlGQOp5DnVlqqll8ENr39YuaVQggxhLNcDjDGD1fNsEcgraiRMNGlQhOnI8uyBFSKGGq+kyaxtkkCGuXvOPcyda4tqIceuCiieXOzIoKi1lLEsiG4oDACzJlhY704fCsvxCc/ebxLaMisMddk/RCOoLajVwsu7QTtt8U/Dw/b5RlzfynjB7QultcpcQU9qmWJJu38WvtV5+HRUoy6ijCRKsi0fFtO0RPRO2nzWadTxt+hNvKX4D0K7lGrJUoeXJPK9jHDxHP1KQdKTtZEMiluBQ1f75TM35QfEaowUX1iQBIuXqMerJpuzCyQfm+qu1elrp5XgDKGObTJLLG4sdvu4lBFdzhrZ64xFdtLWEdGE6YWoMw2UxemG7NF4qg1n9HgqHyIGkZrlaHd/ozhwWULqsHTLFvM9AVksjlu6tKKSTLYLKhIcoPs9PNIp9g8H7gWtoSIlIRnC3/+WaIjVmSZp0aVGCGccDPEU6PIwZXteNXZ8fmgcIaNE6N57f7gIFiUv8zcjIcK1FGTUfSTxu3OSMCW0UQjTXD+i8cINVR6tMhCtpc3DGfqGqCqgNRgMghXlfftPKPu57rXmZ68m6zd39hy29+fPsZMWF1yj/FCQzsnnIDNcV+B5+hCPfc8EVssxTPfzr54uL8iw6RXd1F9I/Cy4XSRfGIx2UWJ3mgx3JJFpBdi4P2JMrL6YpD6nyCbK6qiw7xIp8mivzag0p61Ub6+ehpGa5Wh3f6M4cFlC6rB0yzOXK+jSRXKz66/fkQdOixy7x1rVD95lkmZScgJDgtcrQ==










# enptyKey: A7D90#83Bo6!d1F6


# {
#  "code": 200,
#  "data" : {
#    "isOpen" : 1,
#    "probability" : 10,
#    "wpCodes" : [
#    {
#      "code" : "BVJESF",
#      "id" : "wp001"
#    },
#    {
#      "code" : "TZW3VF",
#      "id" : "wp001"
#    },
#    {
#      "code" : "EZW3VF",
#      "id" : "wp001"
#    },
#    {
#      "code" : "LDJESF",
#      "id" : "wp002"
#    },
#    {
#      "code" : "B9JESF",
#      "id" : "wp003"
#    },
#    {
#      "code" : "W7JESF",
#      "id" : "wp004"
#    }
#    ],
#    "dyCodes" : [
#    {
#      "code" : "Z6D5F",
#      "id" : "dy001"
#    },
#    {
#      "code" : "CBD5F",
#      "id" : "dy002"
#    },
#    {
#      "code" : "CGD5F",
#      "id" : "dy003"
#    },
#    {
#      "code" : "EQD5F",
#      "id" : "dy004"
#    }
#    ]
#  }
#}
